/*
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package xill.lang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XillStandaloneSetup extends XillStandaloneSetupGenerated {
    
	def static void doSetup() {
        new XillStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
